# Generated by Django 5.0 on 2023-12-31 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='exame_este_ano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='explicador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Faculdade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculdade_nome', models.CharField(max_length=150)),
                ('cursos', models.ManyToManyField(blank=True, to='auth_explicamisto.cursos')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='faculdade',
            field=models.ManyToManyField(to='auth_explicamisto.faculdade'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('exame_obrigatorio', models.BooleanField()),
                ('explicadores', models.ManyToManyField(blank=True, related_name='subjects_explicadores', to=settings.AUTH_USER_MODEL)),
                ('explicandos', models.ManyToManyField(blank=True, related_name='subjects_explicandos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
